#!/usr/bin/env fish

set levels

set blank_project '{
	"folders":
	[
		{
			"path": "."
		}
	]
}'

set projfile $HOME/.config/subp/projects

# setup
mkdir -p (dirname $projfile)
if not [ -f $projfile ]
	touch $projfile
end

# if run with an argument, launch that project
if [ (count $argv) -ge 1 ]
	set projname $argv[1]
	cat $projfile | while read dir
		echo a
		set proj $dir/(basename $dir).sublime-project
		echo b
		if [ (basename $dir) = $projname ]
			echo "Opening $proj"
			subl $proj
		end
	end
	exit 1
end

# find a sublime project in the wd or its parents
while [ (pwd) != "/" ]; and [ (pwd) != $HOME ]
	#if the project exists, open it
	if [ -f (basename (pwd)).sublime-project ]
		subl (basename (pwd)).sublime-project
		pwd >> $projfile
		exit 0
	end

	# otherwise, add the level to our list
	set levels $levels (pwd)

	cd ..
end

# create one
echo "No Sublime Text project files found."
echo "Which directory do you want to make one in?"
echo

for i in (seq (count $levels))
	echo $i (basename $levels[$i])
end

echo

function prompt
	echo "Type a directory number, or 0 to exit: "
end

read -p prompt n

if [ $n != 0 ]
	echo $blank_project > $levels[$n]/(basename $levels[$n]).sublime-project
	subl $levels[$n]/(basename $levels[$n]).sublime-project
end
