#!/usr/bin/env fish

set levels

set blank_project '{
	"folders":
	[
		{
			"path": "__PATH__"
		}
	]
}'

set projfile $HOME/.config/subp/project-list

# setup
mkdir -p (dirname $projfile)
if not [ -f $projfile ]
	touch $projfile
end

function abspath
	pushd $argv[1]
	pwd
	popd
end

function get_project_file
	set path (abspath $argv[1])
	echo "$HOME/.config/subp/projects$path.sublime-project"
end

# if run with an argument, launch that project
if [ (count $argv) -ge 1 ]
	set projname $argv[1]
	cat $projfile | while read dir
		echo a
		set proj $dir/(project_file (basename $dir))
		echo b
		if [ (basename $dir) = $projname ]
			echo "Opening $proj"
			subl $proj
		end
	end
	exit 1
end

# find a sublime project in the wd or its parents
while [ (pwd) != "/" ]; and [ (pwd) != $HOME ]
	#if the project exists, open it
	if [ -f (get_project_file (pwd)) ]
		subl (get_project_file (pwd))
		pwd >> $projfile
		exit 0
	end

	# otherwise, add the level to our list
	set levels $levels (pwd)

	cd ..
end

# create one
echo "No Sublime Text project files found."
echo "Which directory do you want to make one in?"
echo

for i in (seq (count $levels))
	echo $i (basename $levels[$i])
end

echo

function prompt
	echo "Type a directory number, or 0 to exit: "
end

read -p prompt n

if [ $n != 0 ]
	set path $levels[$n]
	set projfile (get_project_file $path)
	mkdir -p (dirname $projfile)
	echo $blank_project | sed "s|__PATH__|$path|" > $projfile
	subl $projfile
end
